python convert_obj_three.py -t binary -i ./layout/housesp_000.obj -o ./layout/housesp_000.js
python convert_obj_three.py -t binary -i ./layout/housesp_001.obj -o ./layout/housesp_001.js
python convert_obj_three.py -t binary -i ./layout/housesp_002.obj -o ./layout/housesp_002.js
python convert_obj_three.py -t binary -i ./layout/housesp_003.obj -o ./layout/housesp_003.js
python convert_obj_three.py -t binary -i ./layout/housesp_004.obj -o ./layout/housesp_004.js
python convert_obj_three.py -t binary -i ./layout/housesp_005.obj -o ./layout/housesp_005.js
python convert_obj_three.py -t binary -i ./layout/housesp_006.obj -o ./layout/housesp_006.js
python convert_obj_three.py -t binary -i ./layout/housesp_007.obj -o ./layout/housesp_007.js
python convert_obj_three.py -t binary -i ./layout/housesp_008.obj -o ./layout/housesp_008.js
python convert_obj_three.py -t binary -i ./layout/housesp_009.obj -o ./layout/housesp_009.js
python convert_obj_three.py -t binary -i ./layout/housesp_010.obj -o ./layout/housesp_010.js
python convert_obj_three.py -t binary -i ./layout/housesp_011.obj -o ./layout/housesp_011.js
python convert_obj_three.py -t binary -i ./layout/housesp_012.obj -o ./layout/housesp_012.js
python convert_obj_three.py -t binary -i ./layout/housesp_013.obj -o ./layout/housesp_013.js
python convert_obj_three.py -t binary -i ./layout/housesp_014.obj -o ./layout/housesp_014.js
python convert_obj_three.py -t binary -i ./layout/housesp_015.obj -o ./layout/housesp_015.js
python convert_obj_three.py -t binary -i ./layout/housesp_016.obj -o ./layout/housesp_016.js
python convert_obj_three.py -t binary -i ./layout/housesp_017.obj -o ./layout/housesp_017.js
python convert_obj_three.py -t binary -i ./layout/housesp_018.obj -o ./layout/housesp_018.js
python convert_obj_three.py -t binary -i ./layout/housesp_019.obj -o ./layout/housesp_019.js
python convert_obj_three.py -t binary -i ./layout/housesp_020.obj -o ./layout/housesp_020.js
python convert_obj_three.py -t binary -i ./layout/housesp_021.obj -o ./layout/housesp_021.js
python convert_obj_three.py -t binary -i ./layout/housesp_022.obj -o ./layout/housesp_022.js
python convert_obj_three.py -t binary -i ./layout/housesp_023.obj -o ./layout/housesp_023.js
python convert_obj_three.py -t binary -i ./layout/housesp_024.obj -o ./layout/housesp_024.js
python convert_obj_three.py -t binary -i ./layout/housesp_025.obj -o ./layout/housesp_025.js
python convert_obj_three.py -t binary -i ./layout/housesp_026.obj -o ./layout/housesp_026.js
python convert_obj_three.py -t binary -i ./layout/housesp_027.obj -o ./layout/housesp_027.js
python convert_obj_three.py -t binary -i ./layout/housesp_028.obj -o ./layout/housesp_028.js
python convert_obj_three.py -t binary -i ./layout/housesp_029.obj -o ./layout/housesp_029.js
python convert_obj_three.py -t binary -i ./layout/housesp_030.obj -o ./layout/housesp_030.js
python convert_obj_three.py -t binary -i ./layout/housesp_031.obj -o ./layout/housesp_031.js
python convert_obj_three.py -t binary -i ./layout/housesp_032.obj -o ./layout/housesp_032.js
python convert_obj_three.py -t binary -i ./layout/housesp_033.obj -o ./layout/housesp_033.js
python convert_obj_three.py -t binary -i ./layout/housesp_034.obj -o ./layout/housesp_034.js
python convert_obj_three.py -t binary -i ./layout/housesp_035.obj -o ./layout/housesp_035.js
python convert_obj_three.py -t binary -i ./layout/housesp_036.obj -o ./layout/housesp_036.js
python convert_obj_three.py -t binary -i ./layout/housesp_037.obj -o ./layout/housesp_037.js
python convert_obj_three.py -t binary -i ./layout/housesp_038.obj -o ./layout/housesp_038.js
python convert_obj_three.py -t binary -i ./layout/housesp_039.obj -o ./layout/housesp_039.js
python convert_obj_three.py -t binary -i ./layout/housesp_040.obj -o ./layout/housesp_040.js
python convert_obj_three.py -t binary -i ./layout/housesp_041.obj -o ./layout/housesp_041.js
python convert_obj_three.py -t binary -i ./layout/housesp_042.obj -o ./layout/housesp_042.js
python convert_obj_three.py -t binary -i ./layout/housesp_043.obj -o ./layout/housesp_043.js
python convert_obj_three.py -t binary -i ./layout/housesp_044.obj -o ./layout/housesp_044.js
python convert_obj_three.py -t binary -i ./layout/housesp_045.obj -o ./layout/housesp_045.js
python convert_obj_three.py -t binary -i ./layout/housesp_046.obj -o ./layout/housesp_046.js
python convert_obj_three.py -t binary -i ./layout/housesp_047.obj -o ./layout/housesp_047.js
python convert_obj_three.py -t binary -i ./layout/housesp_048.obj -o ./layout/housesp_048.js
python convert_obj_three.py -t binary -i ./layout/housesp_049.obj -o ./layout/housesp_049.js
python convert_obj_three.py -t binary -i ./layout/housesp_050.obj -o ./layout/housesp_050.js
python convert_obj_three.py -t binary -i ./layout/housesp_051.obj -o ./layout/housesp_051.js
python convert_obj_three.py -t binary -i ./layout/housesp_052.obj -o ./layout/housesp_052.js
python convert_obj_three.py -t binary -i ./layout/housesp_053.obj -o ./layout/housesp_053.js
python convert_obj_three.py -t binary -i ./layout/housesp_054.obj -o ./layout/housesp_054.js
python convert_obj_three.py -t binary -i ./layout/housesp_055.obj -o ./layout/housesp_055.js
python convert_obj_three.py -t binary -i ./layout/housesp_056.obj -o ./layout/housesp_056.js
python convert_obj_three.py -t binary -i ./layout/housesp_057.obj -o ./layout/housesp_057.js
python convert_obj_three.py -t binary -i ./layout/housesp_058.obj -o ./layout/housesp_058.js
python convert_obj_three.py -t binary -i ./layout/housesp_059.obj -o ./layout/housesp_059.js
python convert_obj_three.py -t binary -i ./layout/housesp_060.obj -o ./layout/housesp_060.js
python convert_obj_three.py -t binary -i ./layout/housesp_061.obj -o ./layout/housesp_061.js
python convert_obj_three.py -t binary -i ./layout/housesp_062.obj -o ./layout/housesp_062.js
python convert_obj_three.py -t binary -i ./layout/housesp_063.obj -o ./layout/housesp_063.js
python convert_obj_three.py -t binary -i ./layout/housesp_064.obj -o ./layout/housesp_064.js
python convert_obj_three.py -t binary -i ./layout/housesp_065.obj -o ./layout/housesp_065.js
python convert_obj_three.py -t binary -i ./layout/housesp_066.obj -o ./layout/housesp_066.js
python convert_obj_three.py -t binary -i ./layout/housesp_067.obj -o ./layout/housesp_067.js
python convert_obj_three.py -t binary -i ./layout/housesp_068.obj -o ./layout/housesp_068.js
python convert_obj_three.py -t binary -i ./layout/housesp_069.obj -o ./layout/housesp_069.js
python convert_obj_three.py -t binary -i ./layout/housesp_070.obj -o ./layout/housesp_070.js
python convert_obj_three.py -t binary -i ./layout/housesp_071.obj -o ./layout/housesp_071.js
python convert_obj_three.py -t binary -i ./layout/housesp_072.obj -o ./layout/housesp_072.js
python convert_obj_three.py -t binary -i ./layout/housesp_073.obj -o ./layout/housesp_073.js
python convert_obj_three.py -t binary -i ./layout/housesp_074.obj -o ./layout/housesp_074.js
python convert_obj_three.py -t binary -i ./layout/housesp_075.obj -o ./layout/housesp_075.js
python convert_obj_three.py -t binary -i ./layout/housesp_076.obj -o ./layout/housesp_076.js
python convert_obj_three.py -t binary -i ./layout/housesp_077.obj -o ./layout/housesp_077.js
python convert_obj_three.py -t binary -i ./layout/housesp_078.obj -o ./layout/housesp_078.js
python convert_obj_three.py -t binary -i ./layout/housesp_079.obj -o ./layout/housesp_079.js
python convert_obj_three.py -t binary -i ./layout/housesp_080.obj -o ./layout/housesp_080.js
python convert_obj_three.py -t binary -i ./layout/housesp_081.obj -o ./layout/housesp_081.js
python convert_obj_three.py -t binary -i ./layout/housesp_082.obj -o ./layout/housesp_082.js
python convert_obj_three.py -t binary -i ./layout/housesp_083.obj -o ./layout/housesp_083.js
python convert_obj_three.py -t binary -i ./layout/housesp_084.obj -o ./layout/housesp_084.js
python convert_obj_three.py -t binary -i ./layout/housesp_085.obj -o ./layout/housesp_085.js
python convert_obj_three.py -t binary -i ./layout/housesp_086.obj -o ./layout/housesp_086.js
python convert_obj_three.py -t binary -i ./layout/housesp_087.obj -o ./layout/housesp_087.js
python convert_obj_three.py -t binary -i ./layout/housesp_088.obj -o ./layout/housesp_088.js
python convert_obj_three.py -t binary -i ./layout/housesp_089.obj -o ./layout/housesp_089.js
python convert_obj_three.py -t binary -i ./layout/housesp_090.obj -o ./layout/housesp_090.js
python convert_obj_three.py -t binary -i ./layout/housesp_091.obj -o ./layout/housesp_091.js
python convert_obj_three.py -t binary -i ./layout/housesp_092.obj -o ./layout/housesp_092.js
python convert_obj_three.py -t binary -i ./layout/housesp_093.obj -o ./layout/housesp_093.js
python convert_obj_three.py -t binary -i ./layout/housesp_094.obj -o ./layout/housesp_094.js
python convert_obj_three.py -t binary -i ./layout/housesp_095.obj -o ./layout/housesp_095.js
python convert_obj_three.py -t binary -i ./layout/housesp_096.obj -o ./layout/housesp_096.js
python convert_obj_three.py -t binary -i ./layout/housesp_097.obj -o ./layout/housesp_097.js
python convert_obj_three.py -t binary -i ./layout/housesp_098.obj -o ./layout/housesp_098.js
python convert_obj_three.py -t binary -i ./layout/housesp_099.obj -o ./layout/housesp_099.js
python convert_obj_three.py -t binary -i ./layout/housesp_100.obj -o ./layout/housesp_100.js
python convert_obj_three.py -t binary -i ./layout/housesp_101.obj -o ./layout/housesp_101.js
python convert_obj_three.py -t binary -i ./layout/housesp_102.obj -o ./layout/housesp_102.js
python convert_obj_three.py -t binary -i ./layout/housesp_103.obj -o ./layout/housesp_103.js
python convert_obj_three.py -t binary -i ./layout/housesp_104.obj -o ./layout/housesp_104.js
python convert_obj_three.py -t binary -i ./layout/housesp_105.obj -o ./layout/housesp_105.js
python convert_obj_three.py -t binary -i ./layout/housesp_106.obj -o ./layout/housesp_106.js
python convert_obj_three.py -t binary -i ./layout/housesp_107.obj -o ./layout/housesp_107.js
python convert_obj_three.py -t binary -i ./layout/housesp_108.obj -o ./layout/housesp_108.js
python convert_obj_three.py -t binary -i ./layout/housesp_109.obj -o ./layout/housesp_109.js
python convert_obj_three.py -t binary -i ./layout/housesp_110.obj -o ./layout/housesp_110.js
python convert_obj_three.py -t binary -i ./layout/housesp_111.obj -o ./layout/housesp_111.js
python convert_obj_three.py -t binary -i ./layout/housesp_112.obj -o ./layout/housesp_112.js
python convert_obj_three.py -t binary -i ./layout/housesp_113.obj -o ./layout/housesp_113.js
python convert_obj_three.py -t binary -i ./layout/housesp_114.obj -o ./layout/housesp_114.js
python convert_obj_three.py -t binary -i ./layout/housesp_115.obj -o ./layout/housesp_115.js
python convert_obj_three.py -t binary -i ./layout/housesp_116.obj -o ./layout/housesp_116.js
python convert_obj_three.py -t binary -i ./layout/housesp_117.obj -o ./layout/housesp_117.js
python convert_obj_three.py -t binary -i ./layout/housesp_118.obj -o ./layout/housesp_118.js
python convert_obj_three.py -t binary -i ./layout/housesp_119.obj -o ./layout/housesp_119.js
python convert_obj_three.py -t binary -i ./layout/housesp_120.obj -o ./layout/housesp_120.js
python convert_obj_three.py -t binary -i ./layout/housesp_121.obj -o ./layout/housesp_121.js
python convert_obj_three.py -t binary -i ./layout/housesp_122.obj -o ./layout/housesp_122.js
python convert_obj_three.py -t binary -i ./layout/housesp_123.obj -o ./layout/housesp_123.js
python convert_obj_three.py -t binary -i ./layout/housesp_124.obj -o ./layout/housesp_124.js
python convert_obj_three.py -t binary -i ./layout/housesp_125.obj -o ./layout/housesp_125.js
python convert_obj_three.py -t binary -i ./layout/housesp_126.obj -o ./layout/housesp_126.js
python convert_obj_three.py -t binary -i ./layout/housesp_127.obj -o ./layout/housesp_127.js
python convert_obj_three.py -t binary -i ./layout/housesp_128.obj -o ./layout/housesp_128.js
python convert_obj_three.py -t binary -i ./layout/housesp_129.obj -o ./layout/housesp_129.js
python convert_obj_three.py -t binary -i ./layout/housesp_130.obj -o ./layout/housesp_130.js
python convert_obj_three.py -t binary -i ./layout/housesp_131.obj -o ./layout/housesp_131.js
python convert_obj_three.py -t binary -i ./layout/housesp_132.obj -o ./layout/housesp_132.js
python convert_obj_three.py -t binary -i ./layout/housesp_133.obj -o ./layout/housesp_133.js
python convert_obj_three.py -t binary -i ./layout/housesp_134.obj -o ./layout/housesp_134.js
